// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaFCnyr7Nh7pRxfF3u_VUqpb9df_H9OzM',
    appId: '1:182061417002:web:577ac56ec7286ee8f53953',
    messagingSenderId: '182061417002',
    projectId: 'my-talking-dog-20ba0',
    authDomain: 'my-talking-dog-20ba0.firebaseapp.com',
    storageBucket: 'my-talking-dog-20ba0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtYqH-brwDSlAWoDSODkcSNQmffH9KCO0',
    appId: '1:182061417002:android:51dbc83995b50f13f53953',
    messagingSenderId: '182061417002',
    projectId: 'my-talking-dog-20ba0',
    storageBucket: 'my-talking-dog-20ba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJaxXj9xa1fcST6qKOzIsWVTJ-gCmDPc',
    appId: '1:182061417002:ios:40223bd2c9774938f53953',
    messagingSenderId: '182061417002',
    projectId: 'my-talking-dog-20ba0',
    storageBucket: 'my-talking-dog-20ba0.appspot.com',
    iosBundleId: 'com.example.myTalkingDog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGJaxXj9xa1fcST6qKOzIsWVTJ-gCmDPc',
    appId: '1:182061417002:ios:9d9407a05f4a456cf53953',
    messagingSenderId: '182061417002',
    projectId: 'my-talking-dog-20ba0',
    storageBucket: 'my-talking-dog-20ba0.appspot.com',
    iosBundleId: 'com.example.myTalkingDog.RunnerTests',
  );
}
